repos:
- repo: local
  hooks:
    - id: shfmt
      name: shfmt
      minimum_pre_commit_version: 2.4.0
      language: golang
      additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.3.0]
      entry: shfmt
      args: [-w, -i=2, -ln=bash, -fn, -ci, -sr]
      types: [shell]
    - id: shellcheck
      name: shellcheck
      language: script
      entry: /usr/bin/env shellcheck
      args: [-e, "SC2016,SC2181,SC2034,SC2154,SC2001,SC1090,SC1091,SC2120", -x, --shell=bash]
      types: [shell]
