#!/bin/bash

. $src_script_path/commons.sh --source-only
check_local_configuration

function build_arch {
	echo "building $1..."
	export KBUILD_OUTPUT=${configurations[base_dir]}/drm-misc/$1
	mkdir -p $KBUILD_OUTPUT
	cp ${configurations[base]}/drm-rerere/drm-misc-$1_defconfig $KBUILD_OUTPUT/.config
	make oldconfig
	make $MAKE_OPTS > /dev/null
	echo "Done."
	echo "=============="
}

cd ${configurations[base]}/drm-misc

build_arch x86
ARCH="arm" CROSS_COMPILE="arm-linux-gnu-" build_arch arm
ARCH="arm64" CROSS_COMPILE="aarch64-linux-gnu-" build_arch arm64
