#!/bin/bash

# This is a mock to test the injection of tracing code into kw main file

some_command "$arg1" "$arg2"

#INJECT_CODE_TRACING_SETUP

if [[ "$this_is_an" == 'an if statement' ]]; then
  do_something
fi

function foo()
{
  bar

  #INJECT_CODE_TRACING_COMMIT
}
