#!/bin/bash

function complain
{
  message="$@"
  echo ""
  if [ -t 1 ]; then
    printf $REDCOLOR "$message"
  else
    echo "$message"
  fi
}

function invoke_shunit
{
  command -v shunit2 > /dev/null
  if [[ "$?" -eq 0 ]]; then
    . shunit2
  else
    . ./tests/shunit2
  fi
}
