FROM docker.io/library/fedora

RUN dnf install -y git

COPY ./clone_and_install_kw.sh .

RUN bash ./clone_and_install_kw.sh

# Copy scripts from the "scripts/" folder to a temporary directory
COPY scripts/ /tmp/scripts/

# Grant execution permissions to the copied scripts
RUN chmod +x /tmp/scripts/*

# Move the scripts to /bin
RUN mv /tmp/scripts/* /bin/
