name: Integration tests
on:
  [push, pull_request]

jobs:
  initialize-repository:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

  integration-tests:
    needs: initialize-repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Update the system
        run: sudo apt update -y

      - name: Install dependencies
        run: |
          sudo apt install -y shunit2 podman

      - name: Integration tests
        run: ./run_tests.sh --integration
